theme: jekyll-theme-hacker
title: "rootğŸ’€ArkhAngelLifeJiggy:~#"
description: "Hack. Eat. Sleep. Repeat!!!"
ğŸ” "Many roles, one goal": "Bug Bounty Hunter â€¢ Software Developer â€¢ AI Engineer â€¢ Reverse Engineer â€¢ Prompt Alchemist"
show_downloads: false
show_repo: false

plugins:
  - jekyll-sitemap
